# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/report-server"

# Exclude files which should not be in the output
exclude: [README.md,Gemfile,Gemfile.lock,api_sort.rb,build_kb.rb,switch-ruby.cmd]
navigation:
## List your directory names and order here, like this:
    user-guide:
        position: 110
        title: "User Guide"
    implementer-guide:
        position: 120
        title: "Implementer Guide"
    implementer-guide/licensing-and-distribution:
        position: 130
        title: "Licensing and Distribution"    
    implementer-guide/setup:
        position: 200
        title: "Setup"    
    implementer-guide/user-management:
        position: 210
        title: "User Management"    
    user-guide/reports-management:
        position: 400
        title: "Reports Management" 
    implementer-guide/connecting-to-data:
        position: 600
        title: "Connecting to Data" 
    implementer-guide/apis:
        position: 10000
        title: "APIs"      
    implementer-guide/apis/rest-api:
        position: 10100
        title: "REST API"       
    implementer-guide/apis/rest-api/examples:
        position: 10110
        title: "Examples"    
    implementer-guide/apis/rest-api/v1:
        position: 10120
        title: "V1"  
    implementer-guide/apis/rest-api/v2:
        position: 10130
        title: "V2"  
    implementer-guide/apis/rest-api/examples/javascript:
        position: 10111
        title: "JavaScript"    
    implementer-guide/apis/rest-api/examples/csharp:
        position: 10112
        title: "C#"   
    knowledge-base:
        title: "Knowledge Base"

## The application virtual path
baseurl: /report-server

## The product name
productName: "Report Server"

## The Kendo UI version used
cdnVersion: "2018.1.117"

## The MVC Core version used
mvcCoreVersion: "2018.1.117"

## Progress NPM Registry
registry_url: 'https://registry.npm.telerik.com/'

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "page"
        category: "default"
        product: "report-server"
        editable: true
-
    scope:
        path: "knowledge-base"
    values:
        layout: "kb-page"

## Kendo UI Legacy        
type_links:
    "kendo.Class": "/api/javascript/class"
    "kendo.data.DataSource": "/api/javascript/data/datasource"
    "Array": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array"
    "Blob": "https://developer.mozilla.org/en/docs/Web/API/Blob"
    "File": "https://developer.mozilla.org/en-US/docs/Web/API/File"
    "Boolean": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean"
    "Function": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function"
    "jQuery": "http://api.jquery.com/Types/#jQuery"
    "Promise": "http://api.jquery.com/Types/#Promise"
    "Object": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object"
    "Number": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number"
    "String": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String"
    "Date": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date"
    "Element": "https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement"

# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

# Feedback Form Google Sheet ID
ff-sheet-id: '1BT1fdkj4RPEdq5_lrEN5-x3ln8OVoaUjkYIT3RDdrUU'

# The google services configuration
google_tag_manager: GTM-6X92
google_custom_search: '001595215763381649090:dikfyfm1qqw'
google_custom_kb_search: '001595215763381649090:fkoi6yohnf0'

# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier
    gzip: false

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
